# fly.toml app configuration file generated for marketingnyt on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "marketingnyt"
primary_region = "ams"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "marketingnyt.settings.prod"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "get"
    path = "/healthz"
    port = 8000
    timeout = "5s"
    type = "http"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"

[deploy]
  release_command = "python manage.py migrate --noinput"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
