# Generated by Django 4.2.24 on 2025-10-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL to redirect to (e.g. for podcasts)', null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.category'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='news.category'),
        ),
    ]
