# Generated by Django 4.2.24 on 2025-10-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('news', '0002_articlepage_external_url_alter_articlepage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='cover_video',
            field=models.URLField(blank=True, help_text='Cover video URL (YouTube, Vimeo, or direct video URL). If set, this will be used instead of cover image.', null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for the article (use either image or video, not both)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
